### PR TITLE
Setup Google Authentication

### PR DESCRIPTION
**Pull request by claeusdev**

### CODE REVIEW

**Comment by claeusdev** [comment]
@yawboakye @claudey check this out. after running the new docker settings the structure.sql file changed a bit I don't know why and how.

**Comment by thedumbtechguy** [comment]
Can we implement the open graph markup for jobs too?

https://developers.google.com/search/docs/data-types/job-posting

**Comment by claeusdev** [comment]
@thedumbtechguy we definitely can. I'll have a look at that tonight

**Comment by claudey** [comment]
@claeusdev I am finding it difficult to accept this PR.

Using the job requirements in the description meta tag doesn't seem like a good idea. That field has a best-practice limit of 155, so it's best to use the description of the site for that. Since the job title and company name are unique, they'll match the search queries just well.

Also, the titles are being set for all pages including non-jib, and will be best used in the meta file for referencing as title in SEO.

Also, we're hoping not to add gems for most things we can do ourselves, so we can reduce dependencies.

I wish I could accept this, but I would like to defer, for now.

@silentworks, @yawboakye, thoughts?

**Comment by yawboakye** [comment]
@claeusdev @claudey The current implementation bloats the controller actions, and so I'm not in favor. Metatags should be set in the views (which is to say I'm uncomfortable with using `after_action` to set them either). Secondly, I see `meta-tags` is a popular gem for this sort of thing, but we do really need a gem to just to set metatags?

**Comment by claeusdev** [comment]
@yawboakye @claudey Wonderful... I'll have to find other ways to implement this ...

**Comment by seanmavley** [comment]
@claudey
> Using the job requirements in the description meta tag doesn't seem like a good idea. That field has a best-practice limit of 155

Then perhaps truncating the job requirements to just under the 155 limit, no?

If the meta tag of each job detail page could contain Info about the job, that sounds much better than having a generic devcongress job page descriptions for all the detail job pages

**Comment by claudey** [comment]
@seanmavley I was thinking about that too, but the truth is 155 characters is woefully short to be a preview for a job requirement which sometimes is several paragraphs long.

What just came to mind is we can try two things.
1. Let job posters set a standard 155-character description they can use for each company, when posting jobs. So that means when a user is creating a company, they also specify what short description they want to be shown in search results, or

2. Provide a field in the `new_job` form for job owners to set a job summary, restricted to 155 characters, which will be used to set the description in SEO and SERPs.

@claeusdev Thoughts?

**Comment by seanmavley** [comment]
> 1. Let job posters set a standard 155-character description they can use for each company, when posting jobs. So that means when a user is creating a company, they also specify what short description they want to be shown in search results, or

I think this makes the most sense to me so far. An extra field for job posters. Manual and uninteresting approach, but I think it should do the trick for us. 

And hopefully it's a required field ;)

**Comment by claeusdev** [comment]
@seanmavley @claudey the extra field I don't think would really cut it because people would now have to find the best summary for their post. That wouldn't really help with our own standards for SEO.  There should just be a summary about the job, title and maybe salary. Most people would be posting on the site and hoping to leverage on our reach and SEO leaving that to them to decide would be something else IMO

**Pull request closed without merging**
